liTest run scala.scalanative.junit.ExpectTest started
liTest scala.scalanative.junit.ExpectTest.expectAssert started
ldTest scala.scalanative.junit.ExpectTest.expectAssert finished, took <TIME>
e0scala.scalanative.junit.ExpectTest.expectAssert::::true
liTest scala.scalanative.junit.ExpectTest.expectNormal started
ldTest scala.scalanative.junit.ExpectTest.expectNormal finished, took <TIME>
e0scala.scalanative.junit.ExpectTest.expectNormal::::true
liTest scala.scalanative.junit.ExpectTest.failExpectAssert started
leTest scala.scalanative.junit.ExpectTest.failExpectAssert failed: Expected exception: java.lang.AssertionError, took <TIME>
e2scala.scalanative.junit.ExpectTest.failExpectAssert::java.lang.AssertionError: Expected exception: java.lang.AssertionError::true
ldTest scala.scalanative.junit.ExpectTest.failExpectAssert finished, took <TIME>
liTest scala.scalanative.junit.ExpectTest.failExpectDifferent started
leTest scala.scalanative.junit.ExpectTest.failExpectDifferent failed: Unexpected exception, expected<java.io.IOException> but was<java.lang.IllegalArgumentException>, took <TIME>
leCaused by: java.lang.IllegalArgumentException
e2scala.scalanative.junit.ExpectTest.failExpectDifferent::java.lang.Exception: Unexpected exception, expected<java.io.IOException> but was<java.lang.IllegalArgumentException>::true
ldTest scala.scalanative.junit.ExpectTest.failExpectDifferent finished, took <TIME>
liTest scala.scalanative.junit.ExpectTest.failExpectNoThrow started
leTest scala.scalanative.junit.ExpectTest.failExpectNoThrow failed: Expected exception: java.io.IOException, took <TIME>
e2scala.scalanative.junit.ExpectTest.failExpectNoThrow::java.lang.AssertionError: Expected exception: java.io.IOException::true
ldTest scala.scalanative.junit.ExpectTest.failExpectNoThrow finished, took <TIME>
liTest run scala.scalanative.junit.ExpectTest finished: 3 failed, 0 ignored, 5 total, <TIME>
d
